Algoritmo "dimensões"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/08/2022
Var
largura, comprimento, area: real

Inicio

escreval ("Medida da largura")
leia(largura)

escreval("Medida do comprimento")
leia(comprimento)

area <- (largura*comprimento)

escreval("Medida da area total", area)

Fimalgoritmo