Algoritmo "Exercicio 1"

Var
// Seção de Declarações das variáveis 
   nome: caractere
   ano_at, ano_nc, idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva ("Digite seu nome")
   leia(nome)
   
   escreval("Digite o ano de seu nascimento")
   leia(ano_nc)
   
   escreval ("Digite o ano atual")
   leia(ano_at)
   
   idade <- ano_at - ano_nc
   
   escreval("Seu nome e ", nome)
   
   escreval ("Sua idade e ", idade)

Fimalgoritmo