Algoritmo "Salario"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/08/2022
Var

n1, n2, total: inteiro


Inicio

escreval ("Recebe o salario")
leia(n1)

escreval ("recebe abono")
leia(n2)

total <- (n1+n2)

escreval("Valor total", total)


Fimalgoritmo